name: Unit tests

on:
  pull_request:
    paths:
      - "nextjs/**"
      - ".github/workflows/test.yml"
  push:
    branches:
      - main
    paths:
      - "nextjs/**"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  vitest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nextjs
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: nextjs/package-lock.json
      - run: npm ci --legacy-peer-deps
      - run: npm test
